import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable}`}
      style={{
        margin: 0,
        padding: 0,
        display: "flex",
        flexDirection: "column",
        minHeight: "100vh",
        background: "#f5f5f5",
      }}
    >
    {/* Хедер */}
    <div
      style={{
        background: "#fff",
        padding: "16px",
        textAlign: "center",
        boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      }}
    >
      Header
    </div>

    {/* Контент */}
    <div
      style={{
        flex: 1,
        padding: "16px",
        color: "white",
        background: '#000'
      }}
    >
      {children}
    </div>

    {/* Футер */}
    <div
      style={{
        background: "#fff",
        padding: "16px",
        textAlign: "center",
        marginTop: "auto",
        boxShadow: "0 -2px 4px rgba(0,0,0,0.1)",
      }}
    >
      Footer
    </div>
    </body>
    </html>
  );
}
